# CloudFormation template for Lambda w/ Cron expression
# Peadar Grant

Resources:

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function for scheduled execution
      Handler: index.handle_event
      Runtime: python3.9
      Role: !GetAtt ExecutionRole.Arn
      Code:
        ZipFile: |
          def handle_event(event, context):
            print("EVENT:")
            print(event)
            print("---")
            return { "event": event}
      
  Schedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(1 minute)"
      Targets:
        - Id: 1
          Arn: !GetAtt Function.Arn
  
  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Function.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Schedule.Arn
