# Basic template for DynamoDB table

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: tasks # name of table (can leave blank)
      BillingMode: PAY_PER_REQUEST
      # simple primary key defined by AttributeDefinitions and KeySchema
      AttributeDefinitions:
        -
          AttributeName: name # name of PK attribute
          AttributeType: S # type of PK attribute
      KeySchema:
        -
          AttributeName: name # should be same as above
          KeyType: HASH
