Resources: # must have this section

  privatebucket: # logical name
    Type: AWS::S3::Bucket #must have a type
    
  publicbucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      # using Properties to make a public bucket
    
  queue:
    Properties:
      QueueName: myqueue
    Type: AWS::SQS::Queue
    
  topic:
    Properties:
      TopicName: mytopic
    Type: AWS::SNS::Topic

